### ISSUE TITLE
Support for non-function factories

### ISSUE THREAD

**Issue by captbaritone** [msrose/babel-plugin-transform-amd-to-commonjs#1]
According to https://github.com/amdjs/amdjs-api/blob/master/AMD.md#factory-

> If the factory function returns a value (an object, function, or any value that coerces to true), then that value should be assigned as the exported value for the module.

I've done some work on this, and I have the happy-path working, but there a number of other cases which make a "real" solution a little tough:

## Dependencies

Since any dependencies could not be used to influence the literal return, usually this case would occur without any dependencies. In that case, the expected behavior is pretty simple:

```
define({foo: 'bar'});

// Becomes...

module.exports = {foo: 'bar'};
```

If there are dependencies, we may need to deviate from the existing factory function behavior (which puts the `require()` statements inside the factory function:

```
define(['sideAffector', {foo: 'bar'});

// Becomes...

require('sideAffector');
module.exports = {foo: 'bar'};
```

## Falsy Factories

Other than function factories, I think the only other type we have at Hearsay, are objects. That said, any "truthy" value is apparently valid. Detecting "thuthy" values may be non-trivial (impossible?). I'm not sure what the expected behavior is for non-truthy values... noop? For now, it might be sufficient just to export it whatever it is, even if it's falsy.

**Comment by msrose** [comment]
Thanks for documenting this @captbaritone (missed this issue up til now since somehow I wasn't watching the repo :stuck_out_tongue:)

**Comment by captbaritone** [comment]
It turns out we had few enough examples of non-function factories that it was trivial to simply convert them to the factory syntax. Accordingly, this bug is not a blocker for us.

**Comment by neelav** [comment]
Any chance this issue will get fixed soon?  I'd also like to take advantage of this functionality without having to go back and change our existing code :)

**Comment by msrose** [comment]
@neelav I intend to work on it as soon as I have time, but that likely won't be for 3 weeks at least (exam season is approaching) - subscribe to this thread if you want to get notified of any updates :)

**Comment by neelav** [comment]
sounds good, thanks!

**Comment by captbaritone** [comment]
I've spent some time over the last few days looking into this. The first step I'm taking is going to be moving the `require` statements outside of the factory function. So:

```
define(['stuff'], function(donkeys) {
  return {
    llamas: donkeys.version
  };
});
```

Becomes:

```
 var donkeys = require('stuff');
  module.exports = function() {
    return {
      llamas: donkeys.version
    };
}();
```

This will allow us to handle the non-factory case without having to change how dependencies are loaded. Anyone see any inherent problems with this approach?

I have a branch with this mostly working.

**Comment by msrose** [comment]
Should be no problem - transforming to commonjs mandates one module per file anyway, so adding those variables in the scope above makes no difference. In fact, dependency loading was initially being done outside the IIFE (see https://github.com/msrose/babel-plugin-transform-amd-to-commonjs/commit/53295730679ed583c6ca5ea221647ba6aa9b0b99), but I believe their was no practical reason for moving it inside other than preserving the same scoping behaviour that a define block does.

**Comment by msrose** [comment]
#8
