### ISSUE TITLE
Plugin Breaks When Using Arrow Function in AMD Definition

### ISSUE THREAD

**Issue by philostler** [msrose/babel-plugin-transform-amd-to-commonjs#36]
ES6 arrow functions break the transform.

*With Arrow*
In:
```js
define([
    "underscore",
    "Constants",
    "EventManager",
    "config/process/Config",
    "config/process/CommonConfig"
], (_, Constants, EventManager, Config, CommonConfig) => {
    const obj = {};
    ...
```

Out:
```js
__webpack_require__(3);

__webpack_require__(6);

__webpack_require__(9);

__webpack_require__(558);

__webpack_require__(563);

module.exports = function (_, Constants, EventManager, Config, CommonConfig) {
    var obj = {};
    ...
```

*Without Arrow*
In:
```js
define([
    "underscore",
    "Constants",
    "EventManager",
    "config/process/Config",
    "config/process/CommonConfig"
], function (_, Constants, EventManager, Config, CommonConfig) {
    const obj = {};
    ...
```

Out:
```js
module.exports = function () {
    var _ = __webpack_require__(3);

    var Constants = __webpack_require__(6);

    var EventManager = __webpack_require__(9);

    var Config = __webpack_require__(558);

    var CommonConfig = __webpack_require__(563);

    var obj = {};
    ...
```

**Comment by msrose** [comment]
Thanks for filing the issue @philostler - I'd be happy to add out-of-the-box support for arrow functions. As a temporary workaround, you could try running the plugin after you transform the arrow functions. Since plugins run after presets by default, you might have to create a "local" preset or something to get the ordering to work correctly. Links to some babel docs for reference:
- https://babeljs.io/docs/plugins/#pluginpreset-ordering 
- https://babeljs.io/docs/plugins/#creating-a-preset

**Comment by philostler** [comment]
Wow there's a PR for this already!?!? That's crazy quick! Out of the box support would be awesome, I'd have PR'd it myself but I'm not sure where I'd start with a Babel plugin (never authored one).

Cheers for the links, I tried a few things earlier without much luck. I'm urgently migrating a project off AMD and this plugin is the missing link that's going to save the day! 🥇

**Comment by bschlenk** [comment]
@philostler I was going to create this issue and saw you beat me to it by an hour! So I figured why not fix it?

**Comment by msrose** [comment]
@philostler FYI I'll make a release with the changes from #37 in the next day or so.

**Comment by philostler** [comment]
Thanks @msrose. I've been pulling directly from @bschlenk's branch up to now and all is working great.
