### ISSUE TITLE
Use module-lookup-amd

### ISSUE THREAD

**Issue by DamienCassou** [msrose/babel-plugin-transform-amd-to-commonjs#5]
Thanks for your project, it really helped me. Using [module-lookup-amd](https://www.npmjs.com/package/module-lookup-amd) could make your project even better as, as far as I know, many projects using requirejs have a config file. I've started a little experiment that seems to work ok: https://gitlab.com/ftgp/babel-plugin-transform-amd-to-commonjs/commit/8130701480abd4f5c3915a9030006f240bd21e82 (sorry for the noise in the commit, a tool reformated part of your code). If you like it, I can do a PR.

**Comment by msrose** [comment]
Thanks for filing this issue @DamienCassou, and glad to hear that this project has been useful for you.

Module resolution and config sharing is something I've struggled with before as well; using module-lookup-amd is an interesting solution to this, and definitely seems to be the easiest way. However, I don't think it should be part of this babel plugin itself - ideally this plugin should just be doing amd to commonjs transformations, and module resolution would be done at runtime via something like a config shared between the amd/commonjs environments. So while I don't have a better solution at this point, I don't want to couple module resolution with transforming amd to commonjs, as they are two separate problems. 

An interesting idea might be a separate babel plugin that just does path resolution on require calls in the code - then chaining the plugins would achieve the same effect. (Although I would initially lean towards a config-sharing solution over another babel plugin.)
