### ISSUE TITLE
Extending support for injecting require, module and exports as dependencies

### ISSUE THREAD

**Issue by FransBosuil** [msrose/babel-plugin-transform-amd-to-commonjs#52]
I'm using your plugin to convert my 3th party AMD dependencies. This seems to be working fine for most of the dependencies. However, one of the libraries is 'uglified' and is injecting 'exports' as variable 'a'.  As explained in the caveats, the 'exports' dependencies are skipped. So, variable 'a' is not defined which makes the library faulty.

To resolve the issue, I have cloned your repository, created a branch, added some tests and updated the code base. Unfortunately, I'm not authorized to push my branch to your repository. Can you please give me permission to push the branch? This way, you can validate my changes and merge them if they are acceptable.

**Comment by msrose** [comment]
So the way this normally happens on GitHub is you'll fork this repository so you end up with your own copy that you have write access to. Then you can make a pull request from your fork to the master branch on this repo. Then I'd be happy to review the changes :) Let me know if you run into any problems and I can point you in the right direction.

**Comment by FransBosuil** [comment]
Thank you for the info. PR #53 is available for review.

**Comment by msrose** [comment]
Addressed in #53

**Comment by msrose** [comment]
Available in version [1.2.0](https://www.npmjs.com/package/babel-plugin-transform-amd-to-commonjs/v/1.2.0)
