### ISSUE TITLE
Support for node v4

### ISSUE THREAD

**Issue by PaquitoSoft** [msrose/babel-plugin-transform-amd-to-commonjs#6]
Hi,
We would like to use this module for our project but it's using syntax (ex: object destructuring) which are not supported in version 4 of nodejs.

The basic example is the first line:
`module.exports = ({ types: t }) => {`

So, if you could use a subset of ES2015 features (http://node.green/) this module would be usable from older nodejs versions (unfortunately, we can't update to a newer version).

Thanks.

**Comment by msrose** [comment]
#7
