### ISSUE TITLE
How to tell if the module was AMD

### ISSUE THREAD

**Issue by DominicTobias** [msrose/babel-plugin-transform-amd-to-commonjs#80]
Hi,

Thanks for this excellent plugin. I'd like to find out if the module (well actually raw code) I passed in was in fact AMD. Do you have any ideas how I can do that? I only need to check the top level.

I will look through your code and try and understand it but as you're the expert maybe you know a quick way or some way to  get this lib to tell me.

```js
const { transform } = require('@babel/core');
const requireFromString = require('require-from-string');

const babelOptions = {
  ...
  plugins: [
    'babel-plugin-transform-amd-to-commonjs',
  ],
};

transform(content, babelOptions, (err, result) => {
  const module = requireFromString(result.code);
  // How do I know when the AMD plugin found and parsed the module as AMD?
});
```

**Comment by msrose** [comment]
Hi @DominicTobias - at first thought, an easy way might be to transform the code _without_ the AMD to CommonJS plugin, storing the output as O1, then transforming it again _with_ the plugin, storing the output as O2, then comparing O1 and O2. If O1 != O2, then you can assume that the plugin did something therefore the module is AMD. If O1 == O2 then the plugin did nothing, so as far as it could tell the module was not AMD. I can't think of any immediate reason why that wouldn't work, but there might be some details I'm missing.

At a lower level, the plugin basically assumes that if you have _any_ call in your program that matches the AMD-specified signature of [define](https://github.com/amdjs/amdjs-api/blob/master/AMD.md#define-function-), or any call to require that has an array as its first argument, then you have an AMD module and the plugin will do some sort of transformation. If there aren't any matching calls to define or require, the plugin should do no transformation (hence the recommendation above to compare outputs).

Hope that helps!

**Comment by DominicTobias** [comment]
Thanks that's a smart idea! Though I'm loading the babel/env preset against Node 11 so there is a small chance that some code could be modified. I'll go with the second approach and look for a define sig to be sure.
