### ISSUE TITLE
generates invalid code

### ISSUE THREAD

**Issue by BryanCrotaz** [msrose/babel-plugin-transform-amd-to-commonjs#91]
On line 2, `_exports === undefined`, so `defineProperty` fails
```
var amdDefineResult = function () {
  Object.defineProperty(_exports, "__esModule", {
    value: true
  });
  Object.defineProperty(_exports, "default", {
    enumerable: true,
    get: function () {
      return _animationTemplateDefinition.default;
    }
  });
  var _exports = exports;

  var _animationTemplateDefinition = require("@silvercurve/pixelpipe-ember-data-core/adapters/animation-template-definition");
}();

typeof amdDefineResult !== "undefined" && (module.exports = amdDefineResult);
```

**Comment by msrose** [comment]
Do you have a link to the code before it's transformed? It looks like _exports is being used before it's being defined, and that code does not come from this plugin - everything inside the IIFE being assigned to amdDefineResult is either your application code or coming from another library you're using.

**Comment by msrose** [comment]
@BryanCrotaz do you have any more details on this issue? I can't help debug without more knowledge about what code is being transformed. Please let me know if this is still a problem or if there's any more info you can provide.

**Comment by msrose** [comment]
Closing this issue for now as more information is needed. If anyone runs into similar problems please comment on this issue or open a new one.
